// Code generated by gengencode 25251225 - DO NOT EDIT.

package gencode

func (p Params) Bar() ([]byte, error) {
	return p.execute("bar.tmpl")
}
func (p Params) Foo() ([]byte, error) {
	return p.execute("foo.tmpl")
}
func (p Params) Tridge() ([]byte, error) {
	return p.execute("tridge.tmpl")
}
