#!/bin/ksh
#
# gengencode.t
# Make sure gengencode doesn't overwrite a file with no real changes.
# By J. Stuart McMurray
# Created 20250316
# Last Modified 20250316

set -uo pipefail

. t/shmore.subr

tap_plan 5

OLD=$(mktemp -t) # "Old" methods file
NEW=$(mktemp -t) # New methods file
DATE=25251225    # "Old" generation date

trap 'R=$?; rm "$OLD" "$NEW"; (exit $R); tap_done_testing' EXIT

# gorun runs gengencode as if it were called from go generate.  Arguments are
# passed straight to go run.
function gorun {( cd ./internal/gencode && go run ../gengencode "$@"; )}

# Make an "old" methods file.
gorun | sed -E "1s/[[:digit:]]+/$DATE/" > $OLD
tap_ok $? "Generated old file in $OLD" "$0" $LINENO
GOT=$(head -n1 $OLD)
WANT="// Code generated by gengencode $DATE - DO NOT EDIT."
tap_is "$GOT" "$WANT" "Correct generation date" "$0" $LINENO

# Update it, which shouldn't do anything.
cp "$OLD" "$NEW"
tap_ok $? "Copied old ($OLD) to new ($NEW)" "$0" $LINENO
gorun -write "$NEW"
tap_ok $? "Re-generated new ($NEW)" "$0" $LINENO
GOT=$(diff -u $OLD $NEW)
tap_is "$GOT" "" "File unchanged" "$0" $LINENO

# vim: ft=sh
