// Code generated by gengencode 20250316 - DO NOT EDIT.

package gencode

func (p Params) Basic_tests() ([]byte, error) {
	return p.execute("basic_tests.tmpl")
}
func (p Params) Gitignore() ([]byte, error) {
	return p.execute("gitignore.tmpl")
}
func (p Params) Gotest() ([]byte, error) {
	return p.execute("gotest.tmpl")
}
func (p Params) Library() ([]byte, error) {
	return p.execute("library.tmpl")
}
func (p Params) Libraryreadme() ([]byte, error) {
	return p.execute("libraryreadme.tmpl")
}
func (p Params) Makefile() ([]byte, error) {
	return p.execute("makefile.tmpl")
}
func (p Params) Program() ([]byte, error) {
	return p.execute("program.tmpl")
}
func (p Params) Programreadme() ([]byte, error) {
	return p.execute("programreadme.tmpl")
}
func (p Params) Staticcheck() ([]byte, error) {
	return p.execute("staticcheck.tmpl")
}
